#!/usr/bin/env lua

if not arg[1] then
  io.stderr:write("Usage: " .. arg[0] .." [TYPE]\n" ..
                  "This program reads an xmodmap from standard input, generates a keymap of\n" ..
                  "type TYPE from it and writes it to standard output.\n")
  os.exit(1)
end


output_type = arg[1]
generator = require("generator/" .. output_type)

pattern = "keycode%s*(%d+)%s*=%s*([%w_]+)%s*([%w_]*)%s*([%w_]*)%s*([%w_]*)%s*"

keys = {}

for line in io.lines() do
  _, _, code, sym_normal, sym_shift, sym_ms, sym_ms_shift = string.find(line, pattern)
  if code ~= nil then
    keys[tonumber(code)] = {
      normal = sym_normal,
      shift = sym_shift,
      ms = sym_ms,
      ms_shift = sym_ms_shift
    }
  end
end

generator(keys)
